apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: product-pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: 'localhost:6379'
    - name: redisPassword
      value: ''
    - name: redisDB
      value: '0'
scopes:
  - product-service
